# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "真心话险 - 独立保险经纪人"
email: service@bowxeon.com
description: >- # this means to ignore newlines until "baseurl:"
  独立保险经纪人 - 真心话说保险
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://candy.bowxeon.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: seoktaehyeon

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

timezone: Asia/Shanghai

excerpt_separator: <!--more-->

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .gitignore
  - .github
  - .git
  - Gemfile
  - tool/
  - assets/js/
  - assets/img/
  - assets/posts/
  # - assets/fonts  # EXCLUDE_IN_GITEE_PAGES
  # - _layouts      # EXCLUDE_IN_GITEE_PAGES
  # - _includes     # EXCLUDE_IN_GITEE_PAGES
  # - pagetree.json # EXCLUDE_IN_GITEE_PAGES
  # - 404.md        # EXCLUDE_IN_GITEE_PAGES
  # - search.md     # EXCLUDE_IN_GITEE_PAGES
  # - search.json   # EXCLUDE_IN_GITEE_PAGES
  # - insurance/    # EXCLUDE_IN_GITEE_PAGES
  # - accident/     # EXCLUDE_IN_GITEE_PAGES
  # - medical/      # EXCLUDE_IN_GITEE_PAGES
  # - critical/     # EXCLUDE_IN_GITEE_PAGES
  # - life/         # EXCLUDE_IN_GITEE_PAGES
  # - group/        # EXCLUDE_IN_GITEE_PAGES
  # - author/       # EXCLUDE_IN_GITEE_PAGES

path:
 css: "/assets/css"
 js: "//bowxeon-1303247615.cos.ap-shanghai.myqcloud.com/js"
 img: "//bowxeon-1303247615.cos.ap-shanghai.myqcloud.com/img"
 posts: "//bowxeon-1303247615.cos.ap-shanghai.myqcloud.com/posts/candy"
 logo:
   favicon: "//bowxeon-1303247615.cos.ap-shanghai.myqcloud.com/img/candy/favicon.png"
   header: "//bowxeon-1303247615.cos.ap-shanghai.myqcloud.com/img/candy/logo_text_white.svg"
   footer: "//bowxeon.gitee.io/candy.bowxeon.com/img/candy/logo_text.svg"

theme_color_header: "#395ca3"
theme_color_footer: "#f0f0f0"
theme_color_footer_text: "#70757a"

nav:
  - title: 首页
    id: null
    url: '/'
    target: ''
  - title: 意外险
    id: 'accident'
    url: '/accident'
    target: ''
  - title: 医疗险
    id: 'medical'
    url: '/medical'
    target: ''
  - title: 重疾险
    id: 'critical'
    url: '/critical'
    target: ''
  - title: 寿险
    id: 'life'
    url: '/life'
    target: ''
  - title: 团财险
    id: 'group'
    url: '/group'
    target: ''

beian: 苏ICP备18036961号-1
