name: Docker Image CI

on:
  - push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Login Docker
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMG }}:${{ secrets.IMG_TAG }}
    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMG }}:${{ secrets.IMG_TAG }}
    - name: Re-Tag the Docker image of Alibaba Registry
      run: |
        docker tag ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMG }}:${{ secrets.IMG_TAG }} ${{ secrets.ALI_DC_REGISTRY }}/${{ secrets.ALI_DC_REPO }}/${{ secrets.DOCKER_IMG }}:${{ secrets.IMG_TAG }}
    - name: Login Alibaba Registry
      run: |
        echo "${{ secrets.ALI_DC_PASSWORD }}" | docker login -u ${{ secrets.ALI_DC_USER }} --password-stdin ${{ secrets.ALI_DC_REGISTRY }}
    - name: Push the Alibaba Docker image
      run: |
        docker push ${{ secrets.ALI_DC_REGISTRY }}/${{ secrets.ALI_DC_REPO }}/${{ secrets.DOCKER_IMG }}:${{ secrets.IMG_TAG }}
